AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  
  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  MySqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      QueueName: myqueue.fifo
  GetMessageFromSqs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-message/
      Handler: get-message
      Runtime: go1.x
      MemorySize: 128
      Timeout: 30
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /message
            Method: GET
      Environment:
        Variables:
          PARAM1: VALUE
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt MySqsQueue.QueueName
  SendMessageToSqs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: send-message/
      Handler: send-message
      Runtime: go1.x
      MemorySize: 128
      Timeout: 30
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /message/{name}
            Method: POST
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MySqsQueue.QueueName
Outputs:
  GetMessageAPI:
    Description: "API Gateway endpoint URL for Prod environment for get message from queue"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/message/"
  PostMessageAPI:
    Description: "API Gateway endpoint URL for Prod environment for post message to queue"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/message/"
  MySqsUrl:
    Description: "Demo SQS URL"
    Value: !Ref MySqsQueue 
